"""empty message

Revision ID: 1b4955ec8d25
Revises: 
Create Date: 2025-03-08 21:23:22.186531

"""
from alembic import op
import sqlalchemy as sa
from project.utils.db_types import Embedding


# revision identifiers, used by Alembic.
revision = '1b4955ec8d25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belief',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('embedding', Embedding(dim=1024), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('embedding', Embedding(dim=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interaction',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('personality', Embedding(dim=4), nullable=True),
    sa.Column('personality_confidence', Embedding(dim=4), nullable=True),
    sa.Column('mood_baseline', Embedding(dim=8), nullable=True),
    sa.Column('comm_style', Embedding(dim=5), nullable=True),
    sa.Column('behavior', Embedding(dim=6), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchange',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('interaction_id', sa.Uuid(), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name='interaction_id_exchange_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('embedding', Embedding(dim=512), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('interaction_id', sa.Uuid(), nullable=True),
    sa.Column('updated_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['interaction_id'], ['interaction.id'], name='interaction_id_memory_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('embedding', Embedding(dim=1024), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='category_id_topic_fkey', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('belief_memory',
    sa.Column('belief_id', sa.Uuid(), nullable=False),
    sa.Column('memory_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['belief_id'], ['belief.id'], name='belief_id_memory_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['memory_id'], ['memory.id'], name='belief_memory_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('belief_id', 'memory_id')
    )
    op.create_table('topic_belief',
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('belief_id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['belief_id'], ['belief.id'], name='topic_belief_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name='topic_id_belief_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'belief_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_belief')
    op.drop_table('belief_memory')
    op.drop_table('topic')
    op.drop_table('memory')
    op.drop_table('exchange')
    op.drop_table('interaction')
    op.drop_table('category')
    op.drop_table('belief')
    # ### end Alembic commands ###
