"""empty message

Revision ID: 256cfadc0d3f
Revises: 1b4955ec8d25
Create Date: 2025-03-08 23:07:00.725665

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy.vector import Vector
from project.utils.db_types import Embedding


# revision identifiers, used by Alembic.
revision = '256cfadc0d3f'
down_revision = '1b4955ec8d25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('belief', 'embedding',
               existing_type=Embedding(dim=1024),
               type_=Embedding(dim=512),
               existing_nullable=True)
    op.alter_column('category', 'embedding',
               existing_type=Embedding(dim=1024),
               type_=Embedding(dim=512),
               existing_nullable=True)
    op.alter_column('topic', 'embedding',
               existing_type=Embedding(dim=1024),
               type_=Embedding(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic', 'embedding',
               existing_type=Embedding(dim=512),
               type_=Embedding(dim=1024),
               existing_nullable=True)
    op.alter_column('category', 'embedding',
               existing_type=Embedding(dim=512),
               type_=Embedding(dim=1024),
               existing_nullable=True)
    op.alter_column('belief', 'embedding',
               existing_type=Embedding(dim=512),
               type_=Embedding(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###
